spring:
  profiles: pro
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
server:
  port: 5000
